clients:
    workshops:
        - url: 'http://localhost:9004/api/v2/'
          address: '14 Bury New Rd, Manchester'
          cars:
              - 'Car'
              - 'Truck'
          name: 'manchester'
          type: 'json'
        - url: 'http://localhost:9003/api/v1/'
          address: '1A Gunton Rd, London'
          cars: 'Car'
          name: 'london'
          type: 'xml'
spring:
    mvc:
        format:
            date: 'yyyy-MM-dd'

server:
    error:
        include-message: 'always'
